// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JiraLib.Models;

public partial class attachment
{
    public Guid attachment_id { get; set; }

    public Guid? execution_id { get; set; }

    public Guid? observation_id { get; set; }

    public Guid uploaded_by { get; set; }

    public string file_name { get; set; }

    public string file_extension { get; set; }

    public long file_size_bytes { get; set; }

    public string mime_type { get; set; }

    public string storage_url { get; set; }

    public string storage_provider { get; set; }

    public string description { get; set; }

    public DateTime created_at { get; set; }

    public DateTime updated_at { get; set; }

    public virtual execution execution { get; set; }

    public virtual observation observation { get; set; }

    public virtual user uploaded_byNavigation { get; set; }
}