// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JiraLib.Models;

public partial class device_master
{
    public Guid device_id { get; set; }

    public string device_name { get; set; }

    public string device_type { get; set; }

    public string os_name { get; set; }

    public string os_version { get; set; }

    public string browser_name { get; set; }

    public string browser_version { get; set; }

    public bool is_active { get; set; }

    public DateTime created_at { get; set; }

    public DateTime updated_at { get; set; }

    public virtual ICollection<execution_profile> execution_profiles { get; set; } = new List<execution_profile>();
}