// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JiraLib.Models;

public partial class execution_profile
{
    public Guid profile_id { get; set; }

    public string profile_name { get; set; }

    public string description { get; set; }

    public Guid? device_id { get; set; }

    public Guid? region_id { get; set; }

    public string environment { get; set; }

    public string build_version { get; set; }

    public string config_json { get; set; }

    public Guid created_by { get; set; }

    public bool is_active { get; set; }

    public DateTime created_at { get; set; }

    public DateTime updated_at { get; set; }

    public virtual user created_byNavigation { get; set; }

    public virtual device_master device { get; set; }

    public virtual ICollection<execution> executions { get; set; } = new List<execution>();

    public virtual region_master region { get; set; }
}