// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JiraLib.Models;

public partial class execution_status_master
{
    public Guid status_id { get; set; }

    public string status_code { get; set; }

    public string status_label { get; set; }

    public string description { get; set; }

    public int display_order { get; set; }

    public bool is_active { get; set; }

    public DateTime created_at { get; set; }

    public DateTime updated_at { get; set; }

    public virtual ICollection<execution_status_history> execution_status_historyfrom_statuses { get; set; } = new List<execution_status_history>();

    public virtual ICollection<execution_status_history> execution_status_historyto_statuses { get; set; } = new List<execution_status_history>();

    public virtual ICollection<execution> executions { get; set; } = new List<execution>();
}