// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JiraLib.Models;

public partial class execution
{
    public Guid execution_id { get; set; }

    public Guid ticket_id { get; set; }

    public Guid? profile_id { get; set; }

    public Guid executed_by { get; set; }

    public Guid status_id { get; set; }

    public DateTime execution_date { get; set; }

    public DateTime? started_at { get; set; }

    public DateTime? completed_at { get; set; }

    public int? duration_seconds { get; set; }

    public string test_cycle { get; set; }

    public string notes { get; set; }

    public bool is_regression { get; set; }

    public DateTime created_at { get; set; }

    public DateTime updated_at { get; set; }

    public virtual ICollection<attachment> attachments { get; set; } = new List<attachment>();

    public virtual user executed_byNavigation { get; set; }

    public virtual ICollection<execution_status_history> execution_status_histories { get; set; } = new List<execution_status_history>();

    public virtual ICollection<observation> observations { get; set; } = new List<observation>();

    public virtual execution_profile profile { get; set; }

    public virtual execution_status_master status { get; set; }

    public virtual jira_ticket ticket { get; set; }
}