// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JiraLib.Models;

public partial class execution_status_history
{
    public Guid history_id { get; set; }

    public Guid execution_id { get; set; }

    public Guid? from_status_id { get; set; }

    public Guid to_status_id { get; set; }

    public Guid changed_by { get; set; }

    public string change_reason { get; set; }

    public DateTime changed_at { get; set; }

    public DateTime created_at { get; set; }

    public DateTime updated_at { get; set; }

    public virtual user changed_byNavigation { get; set; }

    public virtual execution execution { get; set; }

    public virtual execution_status_master from_status { get; set; }

    public virtual execution_status_master to_status { get; set; }
}