// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JiraLib.Models;

public partial class jira_ticket
{
    public Guid ticket_id { get; set; }

    public string jira_key { get; set; }

    public string summary { get; set; }

    public string description { get; set; }

    public string ticket_type { get; set; }

    public string priority { get; set; }

    public string jira_status { get; set; }

    public string project_key { get; set; }

    public string reporter_email { get; set; }

    public string assignee_email { get; set; }

    public string sprint_name { get; set; }

    public string fix_version { get; set; }

    public decimal? story_points { get; set; }

    public DateTime? jira_created_at { get; set; }

    public DateTime? jira_updated_at { get; set; }

    public DateTime synced_at { get; set; }

    public DateTime created_at { get; set; }

    public DateTime updated_at { get; set; }

    public virtual ICollection<execution> executions { get; set; } = new List<execution>();
}