// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JiraLib.Models;

public partial class observation_tag
{
    public Guid tag_id { get; set; }

    public Guid observation_id { get; set; }

    public string tag_value { get; set; }

    public Guid created_by { get; set; }

    public DateTime created_at { get; set; }

    public DateTime updated_at { get; set; }

    public virtual user created_byNavigation { get; set; }

    public virtual observation observation { get; set; }
}