// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JiraLib.Models;

public partial class observation
{
    public Guid observation_id { get; set; }

    public Guid execution_id { get; set; }

    public Guid obs_type_id { get; set; }

    public Guid reported_by { get; set; }

    public string title { get; set; }

    public string description { get; set; }

    public string severity { get; set; }

    public string steps_to_repro { get; set; }

    public string expected_result { get; set; }

    public string actual_result { get; set; }

    public string linked_jira_key { get; set; }

    public bool is_resolved { get; set; }

    public DateTime? resolved_at { get; set; }

    public Guid? resolved_by { get; set; }

    public DateTime created_at { get; set; }

    public DateTime updated_at { get; set; }

    public virtual ICollection<attachment> attachments { get; set; } = new List<attachment>();

    public virtual execution execution { get; set; }

    public virtual observation_type_master obs_type { get; set; }

    public virtual ICollection<observation_tag> observation_tags { get; set; } = new List<observation_tag>();

    public virtual user reported_byNavigation { get; set; }

    public virtual user resolved_byNavigation { get; set; }
}