// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JiraLib.Models;

public partial class observation_type_master
{
    public Guid obs_type_id { get; set; }

    public string type_code { get; set; }

    public string type_label { get; set; }

    public string description { get; set; }

    public string severity_default { get; set; }

    public bool is_active { get; set; }

    public DateTime created_at { get; set; }

    public DateTime updated_at { get; set; }

    public virtual ICollection<observation> observations { get; set; } = new List<observation>();
}