// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JiraLib.Models;

public partial class region_master
{
    public Guid region_id { get; set; }

    public string region_code { get; set; }

    public string region_name { get; set; }

    public string country_code { get; set; }

    public string timezone { get; set; }

    public bool is_active { get; set; }

    public DateTime created_at { get; set; }

    public DateTime updated_at { get; set; }

    public virtual ICollection<execution_profile> execution_profiles { get; set; } = new List<execution_profile>();
}