// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace JiraLib.Models;

public partial class TestBridgeDBContext : DbContext
{
    public TestBridgeDBContext(DbContextOptions<TestBridgeDBContext> options)
        : base(options)
    {
    }

    public virtual DbSet<attachment> attachments { get; set; }

    public virtual DbSet<device_master> device_masters { get; set; }

    public virtual DbSet<execution> executions { get; set; }

    public virtual DbSet<execution_profile> execution_profiles { get; set; }

    public virtual DbSet<execution_status_history> execution_status_histories { get; set; }

    public virtual DbSet<execution_status_master> execution_status_masters { get; set; }

    public virtual DbSet<jira_ticket> jira_tickets { get; set; }

    public virtual DbSet<observation> observations { get; set; }

    public virtual DbSet<observation_tag> observation_tags { get; set; }

    public virtual DbSet<observation_type_master> observation_type_masters { get; set; }

    public virtual DbSet<region_master> region_masters { get; set; }

    public virtual DbSet<user> users { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.UseCollation("SQL_Latin1_General_CP1_CI_AS");

        modelBuilder.Entity<attachment>(entity =>
        {
            entity.HasKey(e => e.attachment_id);

            entity.HasIndex(e => e.execution_id, "IX_attachments_execution_id").HasFilter("([execution_id] IS NOT NULL)");

            entity.HasIndex(e => e.observation_id, "IX_attachments_observation_id").HasFilter("([observation_id] IS NOT NULL)");

            entity.HasIndex(e => e.uploaded_by, "IX_attachments_uploaded_by");

            entity.Property(e => e.attachment_id).HasDefaultValueSql("(newid())");
            entity.Property(e => e.created_at).HasDefaultValueSql("(getutcdate())");
            entity.Property(e => e.description).HasMaxLength(500);
            entity.Property(e => e.file_extension)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.file_name)
                .IsRequired()
                .HasMaxLength(500);
            entity.Property(e => e.mime_type).HasMaxLength(200);
            entity.Property(e => e.storage_provider)
                .IsRequired()
                .HasMaxLength(50)
                .HasDefaultValue("AzureBlob");
            entity.Property(e => e.storage_url)
                .IsRequired()
                .HasMaxLength(2000);
            entity.Property(e => e.updated_at).HasDefaultValueSql("(getutcdate())");

            entity.HasOne(d => d.execution).WithMany(p => p.attachments)
                .HasForeignKey(d => d.execution_id)
                .HasConstraintName("FK_attachments_execution");

            entity.HasOne(d => d.observation).WithMany(p => p.attachments)
                .HasForeignKey(d => d.observation_id)
                .HasConstraintName("FK_attachments_observation");

            entity.HasOne(d => d.uploaded_byNavigation).WithMany(p => p.attachments)
                .HasForeignKey(d => d.uploaded_by)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_attachments_uploader");
        });

        modelBuilder.Entity<device_master>(entity =>
        {
            entity.HasKey(e => e.device_id);

            entity.ToTable("device_master");

            entity.Property(e => e.device_id).HasDefaultValueSql("(newid())");
            entity.Property(e => e.browser_name).HasMaxLength(100);
            entity.Property(e => e.browser_version).HasMaxLength(50);
            entity.Property(e => e.created_at).HasDefaultValueSql("(getutcdate())");
            entity.Property(e => e.device_name)
                .IsRequired()
                .HasMaxLength(150);
            entity.Property(e => e.device_type)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.is_active).HasDefaultValue(true);
            entity.Property(e => e.os_name).HasMaxLength(100);
            entity.Property(e => e.os_version).HasMaxLength(50);
            entity.Property(e => e.updated_at).HasDefaultValueSql("(getutcdate())");
        });

        modelBuilder.Entity<execution>(entity =>
        {
            entity.HasKey(e => e.execution_id);

            entity.HasIndex(e => e.execution_date, "IX_executions_exec_date").IsDescending();

            entity.HasIndex(e => e.executed_by, "IX_executions_executed_by");

            entity.HasIndex(e => e.profile_id, "IX_executions_profile_id");

            entity.HasIndex(e => e.status_id, "IX_executions_status_id");

            entity.HasIndex(e => e.ticket_id, "IX_executions_ticket_id");

            entity.Property(e => e.execution_id).HasDefaultValueSql("(newid())");
            entity.Property(e => e.created_at).HasDefaultValueSql("(getutcdate())");
            entity.Property(e => e.execution_date).HasDefaultValueSql("(getutcdate())");
            entity.Property(e => e.test_cycle).HasMaxLength(100);
            entity.Property(e => e.updated_at).HasDefaultValueSql("(getutcdate())");

            entity.HasOne(d => d.executed_byNavigation).WithMany(p => p.executions)
                .HasForeignKey(d => d.executed_by)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_executions_executor");

            entity.HasOne(d => d.profile).WithMany(p => p.executions)
                .HasForeignKey(d => d.profile_id)
                .HasConstraintName("FK_executions_profile");

            entity.HasOne(d => d.status).WithMany(p => p.executions)
                .HasForeignKey(d => d.status_id)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_executions_status");

            entity.HasOne(d => d.ticket).WithMany(p => p.executions)
                .HasForeignKey(d => d.ticket_id)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_executions_ticket");
        });

        modelBuilder.Entity<execution_profile>(entity =>
        {
            entity.HasKey(e => e.profile_id);

            entity.HasIndex(e => e.device_id, "IX_execution_profiles_device_id");

            entity.HasIndex(e => new { e.environment, e.is_active }, "IX_execution_profiles_env");

            entity.HasIndex(e => e.region_id, "IX_execution_profiles_region_id");

            entity.Property(e => e.profile_id).HasDefaultValueSql("(newid())");
            entity.Property(e => e.build_version).HasMaxLength(100);
            entity.Property(e => e.created_at).HasDefaultValueSql("(getutcdate())");
            entity.Property(e => e.description).HasMaxLength(1000);
            entity.Property(e => e.environment)
                .IsRequired()
                .HasMaxLength(50)
                .HasDefaultValue("QA");
            entity.Property(e => e.is_active).HasDefaultValue(true);
            entity.Property(e => e.profile_name)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.updated_at).HasDefaultValueSql("(getutcdate())");

            entity.HasOne(d => d.created_byNavigation).WithMany(p => p.execution_profiles)
                .HasForeignKey(d => d.created_by)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_execution_profiles_creator");

            entity.HasOne(d => d.device).WithMany(p => p.execution_profiles)
                .HasForeignKey(d => d.device_id)
                .HasConstraintName("FK_execution_profiles_device");

            entity.HasOne(d => d.region).WithMany(p => p.execution_profiles)
                .HasForeignKey(d => d.region_id)
                .HasConstraintName("FK_execution_profiles_region");
        });

        modelBuilder.Entity<execution_status_history>(entity =>
        {
            entity.HasKey(e => e.history_id);

            entity.ToTable("execution_status_history");

            entity.HasIndex(e => e.changed_at, "IX_esh_changed_at").IsDescending();

            entity.HasIndex(e => e.execution_id, "IX_esh_execution_id");

            entity.Property(e => e.history_id).HasDefaultValueSql("(newid())");
            entity.Property(e => e.change_reason).HasMaxLength(500);
            entity.Property(e => e.changed_at).HasDefaultValueSql("(getutcdate())");
            entity.Property(e => e.created_at).HasDefaultValueSql("(getutcdate())");
            entity.Property(e => e.updated_at).HasDefaultValueSql("(getutcdate())");

            entity.HasOne(d => d.changed_byNavigation).WithMany(p => p.execution_status_histories)
                .HasForeignKey(d => d.changed_by)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_esh_changed_by");

            entity.HasOne(d => d.execution).WithMany(p => p.execution_status_histories)
                .HasForeignKey(d => d.execution_id)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_esh_execution");

            entity.HasOne(d => d.from_status).WithMany(p => p.execution_status_historyfrom_statuses)
                .HasForeignKey(d => d.from_status_id)
                .HasConstraintName("FK_esh_from_status");

            entity.HasOne(d => d.to_status).WithMany(p => p.execution_status_historyto_statuses)
                .HasForeignKey(d => d.to_status_id)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_esh_to_status");
        });

        modelBuilder.Entity<execution_status_master>(entity =>
        {
            entity.HasKey(e => e.status_id);

            entity.ToTable("execution_status_master");

            entity.HasIndex(e => e.status_code, "UQ_execution_status_master_code").IsUnique();

            entity.Property(e => e.status_id).HasDefaultValueSql("(newid())");
            entity.Property(e => e.created_at).HasDefaultValueSql("(getutcdate())");
            entity.Property(e => e.description).HasMaxLength(500);
            entity.Property(e => e.is_active).HasDefaultValue(true);
            entity.Property(e => e.status_code)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.status_label)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.updated_at).HasDefaultValueSql("(getutcdate())");
        });

        modelBuilder.Entity<jira_ticket>(entity =>
        {
            entity.HasKey(e => e.ticket_id);

            entity.HasIndex(e => e.jira_key, "IX_jira_tickets_jira_key");

            entity.HasIndex(e => e.project_key, "IX_jira_tickets_project_key");

            entity.HasIndex(e => e.synced_at, "IX_jira_tickets_synced_at").IsDescending();

            entity.HasIndex(e => new { e.ticket_type, e.priority }, "IX_jira_tickets_ticket_type");

            entity.HasIndex(e => e.jira_key, "UQ_jira_tickets_key").IsUnique();

            entity.Property(e => e.ticket_id).HasDefaultValueSql("(newid())");
            entity.Property(e => e.assignee_email).HasMaxLength(255);
            entity.Property(e => e.created_at).HasDefaultValueSql("(getutcdate())");
            entity.Property(e => e.fix_version).HasMaxLength(100);
            entity.Property(e => e.jira_key)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.jira_status).HasMaxLength(100);
            entity.Property(e => e.priority)
                .IsRequired()
                .HasMaxLength(20)
                .HasDefaultValue("Medium");
            entity.Property(e => e.project_key).HasMaxLength(50);
            entity.Property(e => e.reporter_email).HasMaxLength(255);
            entity.Property(e => e.sprint_name).HasMaxLength(200);
            entity.Property(e => e.story_points).HasColumnType("decimal(5, 1)");
            entity.Property(e => e.summary)
                .IsRequired()
                .HasMaxLength(1000);
            entity.Property(e => e.synced_at).HasDefaultValueSql("(getutcdate())");
            entity.Property(e => e.ticket_type)
                .IsRequired()
                .HasMaxLength(50)
                .HasDefaultValue("Story");
            entity.Property(e => e.updated_at).HasDefaultValueSql("(getutcdate())");
        });

        modelBuilder.Entity<observation>(entity =>
        {
            entity.HasKey(e => e.observation_id);

            entity.HasIndex(e => e.execution_id, "IX_observations_execution_id");

            entity.HasIndex(e => e.linked_jira_key, "IX_observations_linked_jira").HasFilter("([linked_jira_key] IS NOT NULL)");

            entity.HasIndex(e => e.reported_by, "IX_observations_reported_by");

            entity.HasIndex(e => new { e.severity, e.is_resolved }, "IX_observations_severity");

            entity.Property(e => e.observation_id).HasDefaultValueSql("(newid())");
            entity.Property(e => e.created_at).HasDefaultValueSql("(getutcdate())");
            entity.Property(e => e.linked_jira_key).HasMaxLength(50);
            entity.Property(e => e.severity)
                .IsRequired()
                .HasMaxLength(20)
                .HasDefaultValue("Medium");
            entity.Property(e => e.title)
                .IsRequired()
                .HasMaxLength(500);
            entity.Property(e => e.updated_at).HasDefaultValueSql("(getutcdate())");

            entity.HasOne(d => d.execution).WithMany(p => p.observations)
                .HasForeignKey(d => d.execution_id)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_observations_execution");

            entity.HasOne(d => d.obs_type).WithMany(p => p.observations)
                .HasForeignKey(d => d.obs_type_id)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_observations_type");

            entity.HasOne(d => d.reported_byNavigation).WithMany(p => p.observationreported_byNavigations)
                .HasForeignKey(d => d.reported_by)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_observations_reporter");

            entity.HasOne(d => d.resolved_byNavigation).WithMany(p => p.observationresolved_byNavigations)
                .HasForeignKey(d => d.resolved_by)
                .HasConstraintName("FK_observations_resolver");
        });

        modelBuilder.Entity<observation_tag>(entity =>
        {
            entity.HasKey(e => e.tag_id);

            entity.HasIndex(e => e.observation_id, "IX_observation_tags_obs_id");

            entity.HasIndex(e => e.tag_value, "IX_observation_tags_tag_value");

            entity.HasIndex(e => new { e.observation_id, e.tag_value }, "UQ_observation_tags").IsUnique();

            entity.Property(e => e.tag_id).HasDefaultValueSql("(newid())");
            entity.Property(e => e.created_at).HasDefaultValueSql("(getutcdate())");
            entity.Property(e => e.tag_value)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.updated_at).HasDefaultValueSql("(getutcdate())");

            entity.HasOne(d => d.created_byNavigation).WithMany(p => p.observation_tags)
                .HasForeignKey(d => d.created_by)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_observation_tags_creator");

            entity.HasOne(d => d.observation).WithMany(p => p.observation_tags)
                .HasForeignKey(d => d.observation_id)
                .HasConstraintName("FK_observation_tags_observation");
        });

        modelBuilder.Entity<observation_type_master>(entity =>
        {
            entity.HasKey(e => e.obs_type_id);

            entity.ToTable("observation_type_master");

            entity.HasIndex(e => e.type_code, "UQ_observation_type_master_code").IsUnique();

            entity.Property(e => e.obs_type_id).HasDefaultValueSql("(newid())");
            entity.Property(e => e.created_at).HasDefaultValueSql("(getutcdate())");
            entity.Property(e => e.description).HasMaxLength(500);
            entity.Property(e => e.is_active).HasDefaultValue(true);
            entity.Property(e => e.severity_default).HasMaxLength(20);
            entity.Property(e => e.type_code)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.type_label)
                .IsRequired()
                .HasMaxLength(150);
            entity.Property(e => e.updated_at).HasDefaultValueSql("(getutcdate())");
        });

        modelBuilder.Entity<region_master>(entity =>
        {
            entity.HasKey(e => e.region_id);

            entity.ToTable("region_master");

            entity.HasIndex(e => e.region_code, "UQ_region_master_code").IsUnique();

            entity.Property(e => e.region_id).HasDefaultValueSql("(newid())");
            entity.Property(e => e.country_code).HasMaxLength(10);
            entity.Property(e => e.created_at).HasDefaultValueSql("(getutcdate())");
            entity.Property(e => e.is_active).HasDefaultValue(true);
            entity.Property(e => e.region_code)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.region_name)
                .IsRequired()
                .HasMaxLength(150);
            entity.Property(e => e.timezone).HasMaxLength(100);
            entity.Property(e => e.updated_at).HasDefaultValueSql("(getutcdate())");
        });

        modelBuilder.Entity<user>(entity =>
        {
            entity.HasKey(e => e.user_id);

            entity.HasIndex(e => e.email, "IX_users_email");

            entity.HasIndex(e => e.role, "IX_users_role");

            entity.HasIndex(e => e.username, "IX_users_username");

            entity.HasIndex(e => e.email, "UQ_users_email").IsUnique();

            entity.HasIndex(e => e.username, "UQ_users_username").IsUnique();

            entity.Property(e => e.user_id).HasDefaultValueSql("(newid())");
            entity.Property(e => e.created_at).HasDefaultValueSql("(getutcdate())");
            entity.Property(e => e.email)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.full_name)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.is_active).HasDefaultValue(true);
            entity.Property(e => e.password_hash)
                .IsRequired()
                .HasMaxLength(512);
            entity.Property(e => e.role)
                .IsRequired()
                .HasMaxLength(50)
                .HasDefaultValue("QA");
            entity.Property(e => e.updated_at).HasDefaultValueSql("(getutcdate())");
            entity.Property(e => e.username)
                .IsRequired()
                .HasMaxLength(100);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}