// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JiraLib.Models;

public partial class user
{
    public Guid user_id { get; set; }

    public string username { get; set; }

    public string email { get; set; }

    public string full_name { get; set; }

    public string role { get; set; }

    public string password_hash { get; set; }

    public bool is_active { get; set; }

    public DateTime? last_login_at { get; set; }

    public DateTime created_at { get; set; }

    public DateTime updated_at { get; set; }

    public virtual ICollection<attachment> attachments { get; set; } = new List<attachment>();

    public virtual ICollection<execution_profile> execution_profiles { get; set; } = new List<execution_profile>();

    public virtual ICollection<execution_status_history> execution_status_histories { get; set; } = new List<execution_status_history>();

    public virtual ICollection<execution> executions { get; set; } = new List<execution>();

    public virtual ICollection<observation_tag> observation_tags { get; set; } = new List<observation_tag>();

    public virtual ICollection<observation> observationreported_byNavigations { get; set; } = new List<observation>();

    public virtual ICollection<observation> observationresolved_byNavigations { get; set; } = new List<observation>();
}